services:
    _defaults:
        public: true

    coreshop.order.number_generator.default:
        class: CoreShop\Component\Order\NumberGenerator\SequenceNumberGenerator
        arguments:
            - '@coreshop.sequence.generator'
            - 'order'

    coreshop.quote.number_generator.default:
        class: CoreShop\Component\Order\NumberGenerator\SequenceNumberGenerator
        arguments:
            - '@coreshop.sequence.generator'
            - 'quote'

    CoreShop\Bundle\OrderBundle\Templating\Helper\OrderStateHelperInterface: '@CoreShop\Bundle\OrderBundle\Templating\Helper\OrderStateHelper'
    CoreShop\Bundle\OrderBundle\Templating\Helper\OrderStateHelper:
        arguments:
            - '@coreshop.workflow.state_info_manager'
        tags:
            - { name: templating.helper, alias: coreshop_order_state }

    CoreShop\Bundle\OrderBundle\Twig\OrderStateExtension:
        arguments:
            - '@CoreShop\Bundle\OrderBundle\Templating\Helper\OrderStateHelper'
        tags:
            - { name: twig.extension }
