core_shop_workflow:
    state_machine:
        coreshop_order:
            callbacks:
                after:
                    hold_inventory:
                        on: ['create']
                        do: ['@coreshop.inventory.order_operator', 'hold']
                        args: ['object']
                    cancel_inventory:
                        on: ['cancel']
                        do: ['@coreshop.inventory.order_operator', 'cancel']
                        args: ['object']
        coreshop_order_payment:
            callbacks:
                after:
                    sell_inventory:
                        on: ['pay']
                        do: ['@coreshop.inventory.order_operator', 'sell']
                        args: ['object']
        coreshop_order_sales_type:
            callbacks:
                after:
                    commit_order:
                        on: ['order']
                        do: ['@CoreShop\Component\Order\Committer\OrderCommitterInterface', 'commitOrder']
                        args: ['object']
                    commit_quote:
                        on: ['quote']
                        do: ['@CoreShop\Component\Order\Committer\QuoteCommitterInterface', 'commitOrder']
                        args: ['object']
