imports:
    - { resource: services_alias.yml }
    - { resource: services/form.yml }
    - { resource: services/extension.yml }
    - { resource: services/factory.yml }

services:
    _defaults:
        public: true

    coreshop.form_registry.payum_gateway_config:
        class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

    coreshop.payum.http_client:
        class: Payum\Core\HttpClientInterface
        factory: [Payum\Core\Bridge\Guzzle\HttpClientFactory, create]

    CoreShop\Bundle\PayumBundle\Action\ResolveNextRouteAction:
        tags:
            - { name: payum.action, all: true, alias: coreshop.resolve_next_route }

    CoreShop\Bundle\PayumBundle\Action\ConfirmOrderAction:
        arguments:
            - '@CoreShop\Bundle\WorkflowBundle\Applier\StateMachineApplierInterface'
        tags:
            - { name: payum.action, all: true, alias: coreshop.confirm_order }

    coreshop.payum_action.authorize_payment: '@CoreShop\Bundle\PayumBundle\Action\AuthorizePaymentAction'
    CoreShop\Bundle\PayumBundle\Action\AuthorizePaymentAction:
        arguments:
            - '%coreshop.currency.decimal_factor%'
        tags:
            - { name: payum.action, all: true, alias: coreshop.authorize_payment }

    coreshop.payum_action.capture_payment: '@CoreShop\Bundle\PayumBundle\Action\CapturePaymentAction'
    CoreShop\Bundle\PayumBundle\Action\CapturePaymentAction:
        arguments:
            - '%coreshop.currency.decimal_factor%'
        tags:
            - { name: payum.action, all: true, alias: coreshop.capture_payment }

    coreshop.payum_action.execute_same_request_with_payment_details: '@CoreShop\Bundle\PayumBundle\Action\ExecuteSameRequestWithPaymentDetailsAction'
    CoreShop\Bundle\PayumBundle\Action\ExecuteSameRequestWithPaymentDetailsAction:
        tags:
            - { name: payum.action, all: true }


    # Offline Payment
    CoreShop\Bundle\PayumBundle\Action\Offline\ConvertPaymentAction:
        tags:
            - { name: payum.action, factory: offline, alias: coreshop.offline.convert_payment }

    CoreShop\Bundle\PayumBundle\Action\Offline\ResolveNextRouteAction:
        arguments:
            - '@coreshop.repository.order'
        tags:
            - { name: payum.action, factory: offline, alias: coreshop.offline.resolve_next_route }

    CoreShop\Bundle\PayumBundle\Action\Offline\ConfirmOrderAction:
        arguments:
            - '@CoreShop\Bundle\WorkflowBundle\Applier\StateMachineApplierInterface'
        tags:
            - { name: payum.action, factory: offline, alias: coreshop.offline.confirm_order }

    CoreShop\Bundle\PayumBundle\Action\Offline\StatusAction:
        tags:
            - { name: payum.action, factory: offline, alias: coreshop.offline.status }
